### ISSUE TITLE
Almost-OOM at b.web-connectivity.th.ooni.io

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#260]
Impact: some TH requests were likely not served

Detection: resource consumption alert

Timeline UTC (13 Dec 2018):
06:11 [FIRING] b.web-connectivity.th.ooni.io:9100 has 16% RAM available &mdash; the alert was unnoticed due to ongoing alert fatigue (non-trivial amount of stuff is still half-broken due to unfinished migration)
12:27 [FIRING] b.web-connectivity.th.ooni.io:9100 has 16% RAM available
12:48 @darkk _I suggest to restart, document the incident for future reference and move on_
12:50 @hellais _To be honest dissecting and investigating this issue does not seem like something we should do. That particular section is a monkey patch of the twisted http client to be aligned with the testing logic of probe-legacy_
12:56 [RESOLVED] b.web-connectivity.th.ooni.io:9100 has 16% RAM available

What went wrong:
- `oonib` process had socket leak (that's irrelevant to the incident): ~300 (?) sockets in `lsof` with `can't identify protocol`
- `oonib` process had memory leak: several requests (likely, fetching huge HTTP bodies: over 1.5 GiB of traffic was pumped) consumed significant amount of RAM
![screenshot_2018-12-13 prometheus time series collection and processing server](https://user-images.githubusercontent.com/21046/49964928-cabfa000-ff2c-11e8-9b47-7e7eae3ef621.png)
- `oonib` has not freed memory after the exception. The relevant part of the logs is:
```
2018-12-13T06:12:53+0000 [HTTP11ClientProtocol,client] Unhandled Error
       Traceback (most recent call last):
         File "/usr/local/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 929, in dispatcher
           return func(*args, **kwargs)
         File "/usr/local/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1497, in _finishResponse_WAITING
           self._giveUp(Failure(reason))
         File "/usr/local/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1550, in _giveUp
           self._disconnectParser(reason)
         File "/usr/local/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1538, in _disconnectParser
           parser.connectionLost(reason)
       --- <exception caught here> ---
         File "/usr/local/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 550, in connectionLost
           self.response._bodyDataFinished()
         File "/usr/local/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 929, in dispatcher
           return func(*args, **kwargs)
         File "/usr/local/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1185, in _bodyDataFinished_CONNECTED
           self._bodyProtocol.connectionLost(reason)
         File "/usr/local/lib/python2.7/dist-packages/twisted/web/client.py", line 2115, in connectionLost
           self.deferred.callback(b''.join(self.dataBuffer))
       exceptions.MemoryError:
       
2018-12-13T06:12:54+0000 [HTTPConnection,710280,127.0.0.1] [http] 200 POST / 127.0.0.1 6.86287879944ms
```

What is still unclear:
- [ ] will OOM Killer kill the pid=1 in docker container? It was not the case with Airflow containers. Should something be done?

What could be done to prevent relapse and decrease impact:
- [ ] preventive restart after N handled requests like webservers do?
- [x] improve links from slack to ease alert silencing workflow to reduce alert fatigue

**Comment by darkk** [comment]
Slack messages from the Alertmanager were a bit improved during #265.

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343
